### ISSUE TITLE
How can I install this add on?

### ISSUE THREAD

**Issue by pbastowski** [NitroGhost/vscode-tabulous#3]
I would like to install this add-on in my vscode, but can't find it in the extensions market. 

Is there a manual way of installing that you could share with me?

Thanks.

**Comment by NitroGhost** [comment]
I should be able to release this on the marketplace some time this week. I'll let you know when I do

**Comment by pbastowski** [comment]
Thanks

**Comment by NitroGhost** [comment]
apologies. found some time to publish this, it's now available
